theme: jekyll-theme-cayman
logo: /thumb.jpeg
title: MLBB Jungle 3.0 — Перепрошивка мозга
description: 'Темп → Объект → Клоуз. Мета 2025. Посвящается: Ли🇨🇳, Хаммер🚘, Ламба🚀, Чак😎, Вжик💨'
show_downloads: false
